sudo: true
language: node_js
node_js:
  - '17'
install: npm ci
jobs:
  include:
    - stage: test
      script: bash ./travis/test.sh
    - stage: build
      if: type = push
      script: bash ./travis/build.sh
